---

- hosts: rhel7
  become: true
  become_method: sudo
  become_user: root

  roles:

       - role: rhel7-cis
         when: >
          (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "7") or
          (ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "7") or
          (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] <= "6") or
          (ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] <= "6") or
          (ansible_facts['distribution'] == "OracleLinux" and ansible_facts['distribution_major_version'] <= "6")
         tags: rhel
