---

# 1.1.21 Ensure sticky bit is set on all world-writable directories

- name: 1.1.21 - Ensure sticky bit is set on all world-writable directories - changed_when false
  shell: "df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -type d -perm -0002"
  register: shell_output
  changed_when: false
  tags:
    - section-1
    - "1.1.21"

- name: 1.1.21 - Stdout from the shell command to check for errors
  debug:
    msg: "{{ shell_output.stdout_lines }}"
  tags:
    - section-1
    - "1.1.21"

- name: 1.1.21 - Checking or Setting permissions on the world-writable directories
  file:
    path: "{{ item }}"
    mode: a+t
  with_items:
    - "{{ shell_output.stdout_lines }}"
  failed_when: shell_output.stderr is not defined
  tags:
    - section-1
    - "1.1.21"
