---

# 1.1.1.5 - Ensure mounting of hfsplus filesystems is disabled

- name: 1.1.1.5 - Check if CIS modprobe configuration file exists
  stat:
    path: "{{ cis_modprobe_conf_filename }}"
  register: modprobe_1_1_1_5
  tags:
    - section-1
    - "1.1.1.5"

- name: 1.1.1.5 - Ensure mounting of hfsplus filesystems is disabled
  copy:
    dest: "{{ cis_modprobe_conf_filename }}"
    content: "install hfsplus /bin/true\n"
  when: modprobe_1_1_1_5.stat.exists is not defined or not modprobe_1_1_1_5.stat.exists
  tags:
    - section-1
    - "1.1.1.5"
