---

# 1.1.1.6 - Ensure mounting of squashfs filesystems is disabled

- name: 1.1.1.6 - Check if CIS modprobe configuration file exists
  stat:
    path: "{{ cis_modprobe_conf_filename }}"
  register: modprobe_1_1_1_6
  tags:
    - section-1
    - "1.1.1.6"

- name: 1.1.1.6 - Ensure mounting of squashfs filesystems is disabled
  lineinfile:
    dest: "{{ cis_modprobe_conf_filename }}"
    regexp: "^install squashfs"
    line: "install squashfs /bin/true"
  when: modprobe_1_1_1_6.stat.exists is defined and modprobe_1_1_1_6.stat.exists
  tags:
    - section-1
    - "1.1.1.6"

