---

# 1.1.1.1 - Ensure mounting of cramfs filesystems is disabled

- name: 1.1.1.1 - Check if CIS modprobe configuration file exists
  stat:
    path: "{{ cis_modprobe_conf_filename }}"
  register: modprobe_1_1_1_1
  tags:
    - section-1
    - "1.1.1.1"

- name: 1.1.1.1 - Display registered value
  debug:
    msg: Output value for {{ modprobe_1_1_1_1 }}
  tags:
    - section-1
    - "1.1.1.1"

- name: 1.1.1.1 - Ensure mounting of cramfs filesystems is disabled
  lineinfile:
    dest: "{{ cis_modprobe_conf_filename }}"
    regexp: "^install cramfs"
    line: "install cramfs /bin/true"
  when: modprobe_1_1_1_1.stat.exists is defined and modprobe_1_1_1_1.stat.exists
  tags:
    - section-1
    - "1.1.1.1"
