---

# 1.2.3 Ensure GPG keys are configured

- name: 1.2.3 - Ensure GPG keys are configured
  shell: rpm -q gpg-pubkey --qf '%{name}-%{version}-%{release} --> %{summary}\n'
  register: gpg_pubkey_check
  changed_when: false
  args:
    warn: false
  tags:
    - "1.2.3"

- name: 1.2.3 - Check GPG keys are configured
  debug:
    msg: RPM command output is {{ gpg_pubkey_check.stdout }}
  tags:
    - "1.2.3"
