---

# 1.4.3 - Ensure authentication is required for single user mode

- name: 1.4.3 - Check if sysconfig init file exists
  stat:
    path: "{{ cis_sysconfig_init_filename }}"
  register: sysconfig_init_1_4_3
  tags:
    - "1.4.3"

- name: 1.4.3 - Ensure authentication is required for single-user mode
  copy:
    dest: "{{ cis_sysconfig_init_filename }}"
    content: "SINGLE=/sbin/sulogin\n"
  when: sysconfig_init_1_4_3.stat.exists is not defined or not sysconfig_init_1_4_3.stat.exists
  tags:
    - "1.4.3"

- name: 1.4.3 - Ensure authentication is required for single-user mode
  lineinfile:
    dest: "{{ cis_sysconfig_init_filename }}"
    regexp: "^SINGLE="
    line: "SINGLE=/sbin/sulogin"
  when: sysconfig_init_1_4_3.stat.exists is defined and sysconfig_init_1_4_3.stat.exists
  tags:
    - "1.4.3"
