---

# 1.5.4 Ensure prelink is disabled

- name: 1.5.4 - Check if prelink binary exists
  yum:
    list: prelink
  ignore_errors: true
  register: which_1_5_4
  tags:
    - "1.5.4"

- name: 1.5.4 - Display registered output
  debug:
    msg: Ouput message is {{ which_1_5_4 }}
  tags:
    - "1.5.4"

- name: 1.5.4 - Restore prelinked binaries
  command: prelink -ua
  when: "'installed' in which_1_5_4.results"
  tags:
    - "1.5.4"

- name: 1.5.4 - Ensure prelink is disabled
  yum:
    name: prelink
    state: absent
  tags:
    - "1.5.4"
