---

# 1.5.1 Ensure core dumps are restricted

- name: 1.5.1 - Check if security limits file exists
  stat:
    path: "{{ cis_security_limits_filename }}"
  register: security_limits_1_5_1
  tags:
    - "1.5.1"

- name: 1.5.1 - Ensure core dumps are restricted
  copy:
    dest: "{{ cis_security_limits_filename }}"
    content: "* hard core 0\n"
  when: security_limits_1_5_1.stat.exists is not defined or not security_limits_1_5_1.stat.exists
  tags:
    - "1.5.1"

- name: 1.5.1 - Prevent suid programs from dumping core
  sysctl:
    ignoreerrors: yes
    name: fs.suid_dumpable
    value: 0
    state: present
  tags:
    - "1.5.1"
