---

# 1.5.3 Ensure address space layout randomization (ASLR) is enabled

- name: 1.5.3 - Ensure address space layout randomization is enabled
  sysctl:
    ignoreerrors: yes
    name: kernel.randomize_va_space
    value: 2
    state: present
  tags:
    - "1.5.3"
