---

# 2.1.5 Ensure time services are not enabled

- name: 2.1.5 - Ensure time services are not enabled
  service:
    name: "{{ item }}"
    enabled: false
    state: "{{ cis_time_state }}"
  with_items:
    - time-dgram
    - time-stream
  when:  cis_xinetd_state != 'absent'
  tags:
    - section-2
    - "2.1.5"
