---

- name: 2.2.17 - Ensure rsh server is not enabled
  service:
    name: "{{ item }}"
    enabled: false
    state: stopped
  with_items:
    - rexec
    - rlogin
    - rsh
  ignore_errors: true
  tags:
    - section-2
    - "2.2.17"
