---

# 3.2.7 Ensure Reverse Path Filtering is enabled

- name: 3.2.7 - Ensure Reverse Path Filtering is enabled
  sysctl:
    ignoreerrors: true
    name: "{{ item.kernel_param }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - "{{ cis_v_3_2_7_ipv4_conf_all_rp_filter }}"
    - "{{ cis_v_3_2_7_ipv4_conf_default_rp_filter }}"
  tags:
    - section-3
    - "3.2.7"

- name: 3.2.7 - Get Reverse Path Filtering value from the active kernel parameters
  command: "cat {{ item.proc_src }}"
  register: v_3_2_7_kernel_param
  changed_when: false
  with_items:
    - "{{ cis_v_3_2_7_ipv4_conf_all_rp_filter }}"
  tags:
    - section-3
    - "3.2.7"

- name: 3.2.7 - Displaying value for the all Reverse Path Filtering
  debug:
    msg: The value for kernel_param_value is {{ v_3_2_7_kernel_param.results[0].stdout }}
