---

# 3.4.5 Ensure permissions on /etc/hosts.deny are configured

- name: 3.4.5 - Ensure permissions on /etc/hosts.deny are configured
  file:
    path: "/etc/hosts.deny"
    owner: root
    group: root
    mode: 0644
  tags:
    - section-3
    - "3.4.5"
