---

# 3.5.3 - Ensure RDS is disabled

- name: 3.5.3 - Check if CIS modprobe configuration file exists
  stat:
    path: "{{ cis_modprobe_conf_filename }}"
  register: modprobe_3_5_3
  tags:
    - section-3
    - "3.5.3"

- name: 3.5.3 - Ensure RDS is disabled
  lineinfile:
    dest: "{{ cis_modprobe_conf_filename }}"
    regexp: "^install rds\\s+"
    line: "install rds /bin/true"
  when: modprobe_3_5_3.stat.exists is defined and modprobe_3_5_3.stat.exists
  tags:
    - section-3
    - "3.5.3"
