---

# 3.5.1 - Ensure DCCP is disabled

- name: 3.5.1 - Check if CIS modprobe configuration file exists
  stat:
    path: "{{ cis_modprobe_conf_filename }}"
  register: modprobe_3_5_1
  tags:
    - section-3
    - "3.5.1"

- name: 3.5.1 - Ensure DCCP is disabled
  lineinfile:
    dest: "{{ cis_modprobe_conf_filename }}"
    regexp: "^install dccp\\s+"
    line: "install dccp /bin/true"
  when: modprobe_3_5_1.stat.exists is defined and modprobe_3_5_1.stat.exists
  tags:
    - section-3
    - "3.5.1"
