---

# 4.3 - Ensure logrotate is configured

- name: Install logrotate configuration
  template:
    src: templates/logrotate.conf.j2
    dest: /etc/logrotate.conf
    mode: 0644
    owner: root
    group: root
    backup: true
  tags:
    - section-4
    - "4.3"
