---

# 5.1.1 Ensure cron daemon is enabled

- name: 5.1.1 - Ensure cron is installed
  yum:
    name: cronie
    state: present
  tags:
    - section-5
    - "5.1.1"

- name: 5.1.1 - Ensure cron daemon is enabled
  service:
    name: "crond"
    enabled: true
    state: started
  ignore_errors: false
  tags:
    - section-5
    - "5.1.1"
