---

# 5.2.10 - Ensure SSH PermitUserEnvironment is disabled

- name: Check if /etc/ssh/sshd_config exists
  stat:
    path: /etc/ssh/sshd_config
  register: sshd_config
  tags:
    - section-5
    - "5.2.10"

- name: 5.2.10 - Ensure SSH PermitUserEnvironment is disabled
  lineinfile:
    regexp: "^PermitUserEnvironment\\s+"
    line: "PermitUserEnvironment no"
    dest: "/etc/ssh/sshd_config"
  when: sshd_config.stat.exists
  notify:
    - Restart sshd
  tags:
    - section-5
    - "5.2.10"
