---

# 5.2.8 - Ensure SSH root login is disabled

- name: Check if /etc/ssh/sshd_config exists
  stat:
    path: /etc/ssh/sshd_config
  register: sshd_config
  tags:
    - section-5
    - "5.2.8"

- name: 5.2.8 - Ensure SSH root login is disabled
  lineinfile:
    regexp: "^PermitRootLogin\\s+"
    line: "PermitRootLogin no"
    dest: "/etc/ssh/sshd_config"
  when: sshd_config.stat.exists
  notify:
    - Restart sshd
  tags:
    - section-5_last
    - "5.2.8_last"
