---

# 5.2.7 - Ensure SSH HostbasedAuthentication is disabled

- name: Check if /etc/ssh/sshd_config exists
  stat:
    path: /etc/ssh/sshd_config
  register: sshd_config
  tags:
    - section-5
    - "5.2.7"

- name: 5.2.7 - Ensure SSH HostbasedAuthentication is disabled
  lineinfile:
    regexp: "^HostbasedAuthentication\\s+"
    line: "HostbasedAuthentication no"
    dest: "/etc/ssh/sshd_config"
  when: sshd_config.stat.exists
  notify:
    - Restart sshd
  tags:
    - section-5
    - "5.2.7"
