---

# 5.2.13 - Ensure SSH LoginGraceTime is set to one minute or less

- name: Check if /etc/ssh/sshd_config exists
  stat:
    path: /etc/ssh/sshd_config
  register: sshd_config
  tags:
    - section-5
    - "5.2.13"

- name: 5.2.13 - Ensure SSH LoginGraceTime is set to one minute or less
  lineinfile:
    regexp: "^LoginGraceTime\\s+"
    line: "LoginGraceTime {{ cis_sshd_login_grace_time }}"
    dest: "/etc/ssh/sshd_config"
  when: sshd_config.stat.exists
  notify:
    - Restart sshd
  tags:
    - section-5
    - "5.2.13"
