---

# 5.2.5 -  Ensure SSH MaxAuthTries is set to 4 or less

- name: Check if /etc/ssh/sshd_config exists
  stat:
    path: /etc/ssh/sshd_config
  register: sshd_config
  tags:
    - section-5
    - "5.2.5"

- name: 5.2.5 - Ensure SSH MaxAuthTries is set to 4 or less
  lineinfile:
    regexp: "^MaxAuthTries\\s+"
    line: "MaxAuthTries {{ cis_sshd_max_auth_tries }}"
    dest: "/etc/ssh/sshd_config"
  when: sshd_config.stat.exists
  notify:
    - Restart sshd
  tags:
    - section-5
    - "5.2.5"
