---

# 5.2.3 - Ensure SSH LogLevel is set to INFO

- name: Check if /etc/ssh/sshd_config exists
  stat:
    path: /etc/ssh/sshd_config
  register: sshd_config
  tags:
    - section-5
    - "5.2.3"

- name: 5.2.3 - Ensure SSH LogLevel is set to INFO
  lineinfile:
    regexp: "^LogLevel\\s+"
    line: "LogLevel INFO"
    dest: "/etc/ssh/sshd_config"
  when: sshd_config.stat.exists
  notify:
    - Restart sshd
  tags:
    - section-5
    - "5.2.3"
