---

# 6.1.14 Audit SGID executables

- name: 6.1.14 - Check if any SGID executables exist
  shell: df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -type f -perm -2000
  register: audit_6_1_14
  changed_when: false
  tags:
    - section-6
    - "6.1.14"

- name: 6.1.14 - Audit SGID executables
  fail:
    msg: "{{ audit_6_1_14.stdout }}"
  when:
    - audit_6_1_14.stdout_lines is defined and audit_6_1_14.stdout_lines|length > 0
    - fail_on_manual_remediation_actions
  tags:
    - section-6
    - "6.1.14"
