---

# 6.1.11 Ensure no unowned files or directories exist

- name: 6.1.11 - Audit if any unowned files or directories exist
  shell: df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -nouser
  register: audit_6_1_11
  changed_when: false
  tags:
    - section-6
    - "6.1.11"

- name: 6.1.11 - Ensure no unowned files or directories exist
  fail:
    msg: "{{ audit_6_1_11.stdout_lines }}"
  when:
    - audit_6_1_11.stdout_lines is defined and audit_6_1_11.stdout_lines|length > 0
    - fail_on_manual_remediation_actions
  tags:
    - section-6
    - "6.1.11"
