---

# 6.2.4 Ensure no legacy "+" entries exist in /etc/group

- name: 6.2.4 - Ensure no legacy "+" entries exist in /etc/group
  replace:
    dest: "/etc/group"
    regexp: "^\\+:.*\n"
  tags:
    - section-6
    - "6.2.4"
